### ISSUE TITLE
anoying unused parameters

### ISSUE THREAD

**Issue by Milerius** [veselink1/refl-cpp#4] opened 2019-09-13 07:00 UTC
<img width="1680" alt="Capture d’écran 2019-09-13 à 08 59 42" src="https://user-images.githubusercontent.com/21139416/64843241-dac3f780-d604-11e9-8f0e-b84b9fdbb940.png">

You can use attribute [[maybe_unused]] or remove the variable name in signature of the function to silent the warnings please

**Comment by veselink1** [comment] 2019-09-18 08:16
Thank you for your suggestion! I will be removing the names of the parameters to silence the warnings.

**Comment by veselink1** [comment] 2019-09-22 15:56
The occasions of unused parameters that were not caused by a linter error should be fixed in [v0.6.0](https://github.com/veselink1/refl-cpp/tree/v0.6.0).

**Closed by veselink1** 2019-09-22 15:56 UTC
